In [2]:
import numpy as np
import pandas as pd

# Exercise 5.1: Mastering .loc for Pandas data frames

In [3]:
!head -20 data/frog_tongue_adhesion.csv

# These data are from the paper,
#   Kleinteich and Gorb, Sci. Rep., 4, 5225, 2014.
# It was featured in the New York Times.
#    http://www.nytimes.com/2014/08/25/science/a-frog-thats-a-living-breathing-pac-man.html
#
# The authors included the data in their supplemental information.
#
# Importantly, the ID refers to the identifites of the frogs they tested.
#   I:   adult, 63 mm snout-vent-length (SVL) and 63.1 g body weight,
#        Ceratophrys cranwelli crossed with Ceratophrys cornuta
#   II:  adult, 70 mm SVL and 72.7 g body weight,
#        Ceratophrys cranwelli crossed with Ceratophrys cornuta
#   III: juvenile, 28 mm SVL and 12.7 g body weight, Ceratophrys cranwelli
#   IV:  juvenile, 31 mm SVL and 12.7 g body weight, Ceratophrys cranwelli
date,ID,trial number,impact force (mN),impact time (ms),impact force / body weight,adhesive force (mN),time frog pulls on target (ms),adhesive force / body weight,adhesive impulse (N-s),total contact area (mm2),contact area without mucus (mm2),contact area with mucus / contact area without mucus,contact pressure (Pa),adhesive strength (Pa)
2013_02_26,I,3,1205,46,1.95,-785,884,1.27,-0.290,387,70,0.82,3117,-2030
2013_02_26,I,4,2527,44,4.08,-983,248,1.59,-0.181,101,94,0.07,24923,-9695
2013_03_01,I,1,1745,34,2.82,-850,211,1.37,-0.157,83,79,0.05,21020,-10239
2013_03_01,I,2,1556,41,2.51,-455,1025,0.74,-0.170,330,158,0.52,4718,-1381
2013_03_01,I,3,493,36,0.80,-974,499,1.57,-0.423,245,216,0.12,2012,-3975

a) Load in the data set into a data frame. Be sure to use the appropriate value for the `comment` keyword argument of `pd.read_csv()`.

In [145]:
df = pd.read_csv('data/frog_tongue_adhesion.csv',
                 comment = '#', header = [0])

df.head()

,date,ID,trial number,impact force (mN),impact time (ms),impact force / body weight,adhesive force (mN),time frog pulls on target (ms),adhesive force / body weight,adhesive impulse (N-s),total contact area (mm2),contact area without mucus (mm2),contact area with mucus / contact area without mucus,contact pressure (Pa),adhesive strength (Pa)
0,2013_02_26,I,3,1205,46,1.95,-785,884,1.27,-0.290,387,70,0.82,3117,-2030
1,2013_02_26,I,4,2527,44,4.08,-983,248,1.59,-0.181,101,94,0.07,24923,-9695
2,2013_03_01,I,1,1745,34,2.82,-850,211,1.37,-0.157,83,79,0.05,21020,-10239
3,2013_03_01,I,2,1556,41,2.51,-455,1025,0.74,-0.170,330,158,0.52,4718,-1381
4,2013_03_01,I,3,493,36,0.80,-974,499,1.57,-0.423,245,216,0.12,2012,-3975

b) Extract the impact time of all impacts that had an adhesive strength of magnitude greater than 2000 Pa. 

Note: The data in the `'adhesive strength (Pa)'` column is all negative. This is because the adhesive force is defined to be negative in the measurement. Without changing the data in the data frame, how can you check that the magnitude (the absolute value) is greater than 2000?

In [25]:
df.loc[np.abs(df['adhesive strength (Pa)'])>2000, 'impact time (ms)']

0      46
1      44
2      34
4      36
7      46
8      50
11     48
13     31
14     38
17     60
19     40
23     59
24     33
25     43
27     31
29     42
31     57
33     21
35     29
37     31
38     15
39     42
42    105
44     29
45     16
47     31
49     32
50     30
51     16
52     27
53     30
54     35
55     39
57     34
59     34
60     26
61     20
62     55
65     33
66     74
67     26
68     27
69     33
71      6
73     31
74     34
75     38
78     33
Name: impact time (ms), dtype: int64

c) Extract the impact force and adhesive force for all of Frog II’s strikes.

In [12]:
df.columns

Index(['date', 'ID', 'trial number', 'impact force (mN)', 'impact time (ms)',
       'impact force / body weight', 'adhesive force (mN)',
       'time frog pulls on target (ms)', 'adhesive force / body weight',
       'adhesive impulse (N-s)', 'total contact area (mm2)',
       'contact area without mucus (mm2)',
       'contact area with mucus / contact area without mucus',
       'contact pressure (Pa)', 'adhesive strength (Pa)'],
      dtype='object')

In [17]:
df.loc[df['ID'] == 'II', ['impact force (mN)', 'adhesive force (mN)']]

    impact force (mN)  adhesive force (mN)
20               1612                 -655
21                605                 -292
22                327                 -246
23                946                 -245
24                541                 -553
25               1539                 -664
26                529                 -261
27                628                 -691
28               1453                  -92
29                297                 -566
30                703                 -223
31                269                 -512
32                751                 -227
33                245                 -573
34               1182                 -522
35                515                 -599
36                435                 -364
37                383                 -469
38                457                 -844
39                730                 -648

d) Extract the adhesive force and the time the frog pulls on the target for juvenile frogs (Frogs III and IV). Hint: We saw the `&` operator for Boolean indexing across more than one column. The `|` operator signifies OR, and works analogously. You could also approach this using the `isin()` method of a Pandas `Series`.

In [18]:
df.loc[(df['ID'] == 'III') | (df['ID'] == 'IV'), ['adhesive force (mN)', 'time frog pulls on target (ms)']]

    adhesive force (mN)  time frog pulls on target (ms)
40                  -94                             683
41                 -163                             245
42                 -172                             619
43                 -225                            1823
44                 -301                             918
45                  -93                            1351
46                 -131                            1790
47                 -289                            1006
48                 -104                             883
49                 -229                            1218
50                 -259                             910
51                 -231                             550
52                 -267                            2081
53                 -178                             376
54                 -123                             289
55                 -151                             607
56                 -127                            2932
57                 -372                             680
58                 -236                             685
59                 -390                            1308
60                 -456                             462
61                 -193                             250
62                 -236                             743
63                 -225                             844
64                 -217                             728
65                 -161                             472
66                 -139                             959
67                 -264                             844
68                 -342                            1515
69                 -231                             279
70                 -209                            1427
71                 -292                            2874
72                 -339                            4251
73                 -371                             626
74                 -331                            1254
75                 -302                             986
76                 -216                            1627
77                 -163                            2021
78                 -367                            1366
79                 -218                            1269

# Exercise 5.2: Split-Apply-Combine of the frog data set

a) Compute standard deviation of the impact forces for each frog.

In [23]:
grouped = df.groupby('ID')

grouped['impact force (mN)'].std().reset_index()

    ID  impact force (mN)
0    I         630.207952
1   II         424.573256
2  III         124.273849
3   IV         234.864328

b) Compute the coefficient of variation of the impact forces *and* adhesive forces for each frog.

In [141]:
def coeff_of_var(data):
    """Compute coefficient of variation for an array of data."""""
    return np.std(data) / np.mean(data)

In [147]:
grouped = df[['ID', 'impact force (mN)', 'adhesive force (mN)']].groupby('ID')
grouped.agg(coeff_of_var).reset_index()

    ID  impact force (mN)  adhesive force (mN)
0    I           0.401419            -0.247435
1   II           0.585033            -0.429701
2  III           0.220191            -0.415435
3   IV           0.546212            -0.308042

c) Compute a data frame that has the mean, median, standard deviation, and coefficient of variation of the impact forces and adhesive forces for each frog.

In [129]:
df_mean = grouped[['impact force (mN)', 'adhesive force (mN)']].mean()
df_med = grouped[['impact force (mN)', 'adhesive force (mN)']].median()
df_std = grouped[['impact force (mN)', 'adhesive force (mN)']].std()
df_cov = grouped[['impact force (mN)', 'adhesive force (mN)']].agg(coeff_of_var)

In [137]:
df_stats = pd.concat([df_mean, df_med, df_std, df_cov], axis=1)
df_stats

,impact force (mN),adhesive force (mN),impact force (mN),adhesive force (mN),impact force (mN),adhesive force (mN),impact force (mN),adhesive force (mN)
ID,,,,,,,,
I,1530.20,-658.40,1550.5,-664.5,630.207952,167.143619,0.401419,-0.247435
II,707.35,-462.30,573.0,-517.0,424.573256,203.811600,0.585033,-0.429701
III,550.10,-206.75,544.0,-201.5,124.273849,88.122448,0.220191,-0.415435
IV,419.10,-263.60,460.5,-233.5,234.864328,83.309442,0.546212,-0.308042

In [138]:
header = pd.MultiIndex.from_product([['mean', 'median', 'std', 'cov'],
                                     ['impact force (mN)','adhesive force (mN)']
                                     ]
                                   )


# Reset column names
df_stats.columns = range(df_stats.shape[1])

# Apply descriptive column multi-index
df_stats.columns = header
df_stats = df_stats.reset_index()
df_stats

    ID              mean                                median  \
       impact force (mN) adhesive force (mN) impact force (mN)
0    I           1530.20             -658.40            1550.5
1   II            707.35             -462.30             573.0
2  III            550.10             -206.75             544.0
3   IV            419.10             -263.60             460.5

                                    std                                   cov  \
  adhesive force (mN) impact force (mN) adhesive force (mN) impact force (mN)
0              -664.5        630.207952          167.143619          0.401419
1              -517.0        424.573256          203.811600          0.585033
2              -201.5        124.273849           88.122448          0.220191
3              -233.5        234.864328           83.309442          0.546212


  adhesive force (mN)
0           -0.247435
1           -0.429701
2           -0.415435
3           -0.308042

In [152]:
df_stats = grouped.agg([np.mean, np.median, np.std, coeff_of_var]).reset_index()
df_stats

    ID impact force (mN)                                  adhesive force (mN)  \
                    mean  median         std coeff_of_var                mean
0    I           1530.20  1550.5  630.207952     0.401419             -658.40
1   II            707.35   573.0  424.573256     0.585033             -462.30
2  III            550.10   544.0  124.273849     0.220191             -206.75
3   IV            419.10   460.5  234.864328     0.546212             -263.60


  median         std coeff_of_var
0 -664.5  167.143619    -0.247435
1 -517.0  203.811600    -0.429701
2 -201.5   88.122448    -0.415435
3 -233.5   83.309442    -0.308042

d) Now tidy this data frame.

In [155]:
pd.melt(df_stats,
        id_vars = ['ID'],
        var_name = ['measurement', 'stat']
       )

     ID          measurement          stat        value
0     I    impact force (mN)          mean  1530.200000
1    II    impact force (mN)          mean   707.350000
2   III    impact force (mN)          mean   550.100000
3    IV    impact force (mN)          mean   419.100000
4     I    impact force (mN)        median  1550.500000
5    II    impact force (mN)        median   573.000000
6   III    impact force (mN)        median   544.000000
7    IV    impact force (mN)        median   460.500000
8     I    impact force (mN)           std   630.207952
9    II    impact force (mN)           std   424.573256
10  III    impact force (mN)           std   124.273849
11   IV    impact force (mN)           std   234.864328
12    I    impact force (mN)  coeff_of_var     0.401419
13   II    impact force (mN)  coeff_of_var     0.585033
14  III    impact force (mN)  coeff_of_var     0.220191
15   IV    impact force (mN)  coeff_of_var     0.546212
16    I  adhesive force (mN)          mean  -658.400000
17   II  adhesive force (mN)          mean  -462.300000
18  III  adhesive force (mN)          mean  -206.750000
19   IV  adhesive force (mN)          mean  -263.600000
20    I  adhesive force (mN)        median  -664.500000
21   II  adhesive force (mN)        median  -517.000000
22  III  adhesive force (mN)        median  -201.500000
23   IV  adhesive force (mN)        median  -233.500000
24    I  adhesive force (mN)           std   167.143619
25   II  adhesive force (mN)           std   203.811600
26  III  adhesive force (mN)           std    88.122448
27   IV  adhesive force (mN)           std    83.309442
28    I  adhesive force (mN)  coeff_of_var    -0.247435
29   II  adhesive force (mN)  coeff_of_var    -0.429701
30  III  adhesive force (mN)  coeff_of_var    -0.415435
31   IV  adhesive force (mN)  coeff_of_var    -0.308042

# Exercise 5.3: Adding data to a data frame

We continue working with the frog tongue data. Recall that the header comments in the data file contained information about the frogs. Each frog has associated with it an age (adult or juvenile), snout-vent-length (SVL), body weight, and species (either cross or *cranwelli*). For a tidy data frame, we should have a column for each of these values. Your task is to load in the data, and then add these columns to the data frame. For convenience, here is a data frame with data about each frog.

In [159]:
df_frog = pd.DataFrame(
    data={
        "ID": ["I", "II", "III", "IV"],
        "age": ["adult", "adult", "juvenile", "juvenile"],
        "SVL (mm)": [63, 70, 28, 31],
        "weight (g)": [63.1, 72.7, 12.7, 12.7],
        "species": ["cross", "cross", "cranwelli", "cranwelli"],
    }
)

df_frog

    ID       age  SVL (mm)  weight (g)    species
0    I     adult        63        63.1      cross
1   II     adult        70        72.7      cross
2  III  juvenile        28        12.7  cranwelli
3   IV  juvenile        31        12.7  cranwelli

In [157]:
df.head()

,date,ID,trial number,impact force (mN),impact time (ms),impact force / body weight,adhesive force (mN),time frog pulls on target (ms),adhesive force / body weight,adhesive impulse (N-s),total contact area (mm2),contact area without mucus (mm2),contact area with mucus / contact area without mucus,contact pressure (Pa),adhesive strength (Pa)
0,2013_02_26,I,3,1205,46,1.95,-785,884,1.27,-0.290,387,70,0.82,3117,-2030
1,2013_02_26,I,4,2527,44,4.08,-983,248,1.59,-0.181,101,94,0.07,24923,-9695
2,2013_03_01,I,1,1745,34,2.82,-850,211,1.37,-0.157,83,79,0.05,21020,-10239
3,2013_03_01,I,2,1556,41,2.51,-455,1025,0.74,-0.170,330,158,0.52,4718,-1381
4,2013_03_01,I,3,493,36,0.80,-974,499,1.57,-0.423,245,216,0.12,2012,-3975

In [163]:
df_merged = pd.merge(df_frog, df)

df_merged.head()

,ID,age,SVL (mm),weight (g),species,date,trial number,impact force (mN),impact time (ms),impact force / body weight,adhesive force (mN),time frog pulls on target (ms),adhesive force / body weight,adhesive impulse (N-s),total contact area (mm2),contact area without mucus (mm2),contact area with mucus / contact area without mucus,contact pressure (Pa),adhesive strength (Pa)
0,I,adult,63,63.1,cross,2013_02_26,3,1205,46,1.95,-785,884,1.27,-0.290,387,70,0.82,3117,-2030
1,I,adult,63,63.1,cross,2013_02_26,4,2527,44,4.08,-983,248,1.59,-0.181,101,94,0.07,24923,-9695
2,I,adult,63,63.1,cross,2013_03_01,1,1745,34,2.82,-850,211,1.37,-0.157,83,79,0.05,21020,-10239
3,I,adult,63,63.1,cross,2013_03_01,2,1556,41,2.51,-455,1025,0.74,-0.170,330,158,0.52,4718,-1381
4,I,adult,63,63.1,cross,2013_03_01,3,493,36,0.80,-974,499,1.57,-0.423,245,216,0.12,2012,-3975

In [164]:
%load_ext watermark
%watermark -v -p numpy,pandas,jupyterlab

CPython 3.7.7
IPython 7.13.0

numpy 1.18.1
pandas 0.24.2
jupyterlab 1.2.6