In [2]:
import numpy as np
import pandas as pd

In [3]:
df = pd.read_csv('data/gfmt_sleep.csv', na_values='*')

type(df)

pandas.core.frame.DataFrame

In [4]:
df.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
0,8,f,39,65,80,72.5,91.0,90.0,93.0,83.5,93.0,90.0,9,13,2
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50.0,75.0,50.0,4,11,7
2,18,f,31,90,95,92.5,89.5,90.0,86.0,81.0,89.0,88.0,10,9,3
3,22,f,35,100,75,87.5,89.5,NaN,71.0,80.0,88.0,80.0,13,8,20
4,27,f,74,60,65,62.5,68.5,49.0,61.0,49.0,65.0,49.0,13,9,12

Data frames are indexed by column.

In [5]:
df['percent correct']

0       72.5
1       90.0
2       92.5
3       87.5
4       62.5
5       50.0
6       82.5
7       67.5
8       90.0
9       75.0
10      62.5
11      95.0
12      80.0
13      80.0
14      65.0
15      70.0
16      70.0
17      80.0
18      85.0
19      75.0
20      70.0
21      97.5
22      87.5
23      45.0
24      70.0
25      72.5
26      85.0
27      75.0
28      67.5
29      95.0
       ...
72      87.5
73      97.5
74      92.5
75     100.0
76      60.0
77      95.0
78      77.5
79      77.5
80      82.5
81      40.0
82      87.5
83      85.0
84      87.5
85      77.5
86      62.5
87      72.5
88      85.0
89      92.5
90      85.0
91      72.5
92      90.0
93      90.0
94      55.0
95      87.5
96      60.0
97      77.5
98      87.5
99      75.0
100     70.0
101     62.5
Name: percent correct, Length: 102, dtype: float64

Row indices need not be numbers (although here Pandas automatically assigned them to be numbers here).

# Boolean indexing

In [6]:
df.loc[df['participant number']==27, 'percent correct']

4    62.5
Name: percent correct, dtype: float64

In [7]:
df['participant number'] == 27

0      False
1      False
2      False
3      False
4       True
5      False
6      False
7      False
8      False
9      False
10     False
11     False
12     False
13     False
14     False
15     False
16     False
17     False
18     False
19     False
20     False
21     False
22     False
23     False
24     False
25     False
26     False
27     False
28     False
29     False
       ...
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
Name: participant number, Length: 102, dtype: bool

In [8]:
df.loc[df['gender']=='f', 'percent correct']

0       72.5
2       92.5
3       87.5
4       62.5
5       50.0
8       90.0
9       75.0
10      62.5
11      95.0
12      80.0
13      80.0
14      65.0
15      70.0
16      70.0
17      80.0
20      70.0
22      87.5
23      45.0
24      70.0
25      72.5
26      85.0
27      75.0
28      67.5
29      95.0
30      87.5
31      92.5
33     100.0
34      70.0
38      85.0
40      92.5
       ...
63      85.0
65      85.0
66      85.0
67      85.0
69      90.0
70     100.0
71      85.0
72      87.5
73      97.5
74      92.5
75     100.0
76      60.0
77      95.0
78      77.5
79      77.5
80      82.5
82      87.5
83      85.0
85      77.5
86      62.5
87      72.5
88      85.0
89      92.5
94      55.0
96      60.0
97      77.5
98      87.5
99      75.0
100     70.0
101     62.5
Name: percent correct, Length: 74, dtype: float64

In [9]:
df.loc[df['age']>50, 'percent correct']

4     62.5
5     50.0
7     67.5
9     75.0
16    70.0
36    77.5
44    80.0
53    72.5
59    80.0
65    85.0
67    85.0
72    87.5
80    82.5
91    72.5
92    90.0
96    60.0
98    87.5
Name: percent correct, dtype: float64

In [10]:
df.loc[df['age']>50, :]

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
4,27,f,74,60,65,62.5,68.5,49.0,61.0,49.0,65.0,49.0,13,9,12
5,28,f,61,80,20,50.0,71.0,63.0,31.0,72.5,64.5,70.5,15,14,2
7,33,m,62,45,90,67.5,54.0,37.0,65.0,81.5,62.0,61.0,14,9,9
9,35,f,53,100,50,75.0,74.5,NaN,60.5,65.0,71.0,65.0,14,8,7
16,76,f,61,100,40,70.0,69.5,NaN,44.5,73.0,54.5,73.0,16,4,12
36,13,m,53,95,60,77.5,40.0,33.0,56.0,49.0,47.0,44.0,31,2,11
44,24,f,64,75,85,80.0,50.0,25.0,66.0,24.0,63.0,24.5,20,9,4
53,40,m,53,65,80,72.5,54.0,32.0,47.5,78.5,48.0,51.0,29,3,7
59,50,m,54,90,70,80.0,90.0,83.5,77.5,69.0,88.0,79.0,22,6,16
65,57,f,53,95,75,85.0,84.0,55.0,68.0,61.0,78.5,58.0,24,5,4
67,59,f,67,95,75,85.0,70.0,7.0,69.0,60.0,69.0,59.5,17,7,12
72,64,f,69,95,80,87.5,80.0,65.0,78.5,70.5,80.0,70.0,31,1,1
80,73,f,74,85,80,82.5,66.0,55.0,63.0,50.5,65.0,55.0,20,1,5
91,88,m,66,60,85,72.5,67.5,66.0,74.0,57.0,74.0,64.0,30,5,9
92,91,m,62,100,80,90.0,81.0,NaN,74.5,82.0,79.5,82.0,32,2,1
96,96,f,56,70,50,60.0,63.0,52.5,67.5,65.5,64.0,59.5,26,6,7
98,98,f,70,90,85,87.5,65.5,85.5,87.0,80.0,74.0,80.0,19,8,7

In [11]:
df.loc[(df['age'] < 21) & (df['gender'] == 'f'), :]

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
27,3,f,16,70,80,75.0,70.0,57.0,54.0,53.0,57.0,54.5,23,1,3
29,5,f,18,90,100,95.0,76.5,83.0,80.0,NaN,80.0,83.0,21,7,5
66,58,f,16,85,85,85.0,55.0,30.0,50.0,40.0,52.5,35.0,29,2,11
79,72,f,18,80,75,77.5,67.5,51.5,66.0,57.0,67.0,53.0,29,4,6
88,85,f,18,85,85,85.0,93.0,92.0,91.0,89.0,91.5,91.0,25,4,21

The `&` is a bitwise operator, so you need to put both criteria in parentheses.

For bitwise OR, we use `|`.

In [12]:
inds = (df['age'] < 30) & (df['gender'] == 'f') & (df['percent correct'] > 85)

df.loc[inds, :]

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
22,93,f,28,100,75,87.5,89.5,NaN,67.0,60.0,80.0,60.0,16,7,4
29,5,f,18,90,100,95.0,76.5,83.0,80.0,NaN,80.0,83.0,21,7,5
30,6,f,28,95,80,87.5,100.0,85.0,94.0,61.0,99.0,65.0,19,7,12
33,10,f,25,100,100,100.0,90.0,NaN,85.0,NaN,90.0,NaN,17,10,11
56,44,f,21,85,90,87.5,66.0,29.0,70.0,29.0,67.0,29.0,26,7,18
58,48,f,23,90,85,87.5,67.0,47.0,69.0,40.0,67.0,40.0,18,6,8
60,51,f,24,85,95,90.0,97.0,41.0,74.0,73.0,83.0,55.5,29,1,7
75,67,f,25,100,100,100.0,61.5,NaN,58.5,NaN,60.5,NaN,28,8,9

An insomniac is a person with Sleep Condition Indicator <= 16. Let's calculate if each participant is an insomniac.

In [13]:
df['sci'] <= 16

0       True
1       True
2       True
3       True
4       True
5       True
6       True
7       True
8       True
9       True
10      True
11      True
12      True
13      True
14      True
15      True
16      True
17      True
18      True
19      True
20      True
21      True
22      True
23      True
24      True
25     False
26     False
27     False
28     False
29     False
       ...
72     False
73     False
74     False
75     False
76     False
77     False
78     False
79     False
80     False
81     False
82     False
83     False
84     False
85     False
86     False
87     False
88     False
89     False
90     False
91     False
92     False
93     False
94     False
95     False
96     False
97     False
98     False
99     False
100    False
101    False
Name: sci, Length: 102, dtype: bool

Add it to the dataframe:

In [14]:
df['insomnia'] = df['sci'] <= 16

df.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess,insomnia
0,8,f,39,65,80,72.5,91.0,90.0,93.0,83.5,93.0,90.0,9,13,2,True
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50.0,75.0,50.0,4,11,7,True
2,18,f,31,90,95,92.5,89.5,90.0,86.0,81.0,89.0,88.0,10,9,3,True
3,22,f,35,100,75,87.5,89.5,NaN,71.0,80.0,88.0,80.0,13,8,20,True
4,27,f,74,60,65,62.5,68.5,49.0,61.0,49.0,65.0,49.0,13,9,12,True

In [15]:
df.loc[df['insomnia'], 'percent correct']

0     72.5
1     90.0
2     92.5
3     87.5
4     62.5
5     50.0
6     82.5
7     67.5
8     90.0
9     75.0
10    62.5
11    95.0
12    80.0
13    80.0
14    65.0
15    70.0
16    70.0
17    80.0
18    85.0
19    75.0
20    70.0
21    97.5
22    87.5
23    45.0
24    70.0
Name: percent correct, dtype: float64

In [16]:
# Mean percent correct for people with insomnia
np.mean(df.loc[df['insomnia'], 'percent correct'])

76.1

In [17]:
# Mean percent correct for people without insomnia
np.mean(df.loc[~df['insomnia'],'percent correct'])

81.46103896103897

In [18]:
# Summary statistics for the whole dataframe
df.describe()

,participant number,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
count,102.000000,102.000000,102.000000,102.000000,102.000000,102.000000,84.000000,102.000000,93.000000,102.000000,99.000000,102.000000,102.000000,102.000000
mean,52.049020,37.921569,83.088235,77.205882,80.147059,74.990196,58.565476,71.137255,61.220430,74.642157,61.979798,22.245098,5.274510,7.294118
std,30.020909,14.029450,15.091210,17.569854,12.047881,14.165916,19.560653,14.987479,17.671283,13.619725,15.921670,7.547128,3.404007,4.426715
min,1.000000,16.000000,35.000000,20.000000,40.000000,29.500000,7.000000,19.000000,17.000000,24.000000,24.500000,0.000000,0.000000,0.000000
25%,26.250000,26.500000,75.000000,70.000000,72.500000,66.000000,46.375000,64.625000,50.000000,66.000000,51.000000,17.000000,3.000000,4.000000
50%,52.500000,36.500000,90.000000,80.000000,83.750000,75.000000,56.250000,71.250000,61.000000,75.750000,61.500000,23.500000,5.000000,7.000000
75%,77.750000,45.000000,95.000000,90.000000,87.500000,86.500000,73.500000,80.000000,74.000000,82.375000,73.000000,29.000000,7.000000,10.000000
max,103.000000,74.000000,100.000000,100.000000,100.000000,100.000000,92.000000,100.000000,100.000000,100.000000,100.000000,32.000000,15.000000,21.000000

In [19]:
# Output data to .csv file
df.to_csv('data/gfmt_sleep_with_insomnia.csv', index=False)

# Tidy data

1. Each variable is a column.
2. Each observation is a row.
3. Each type of observation has its own separate data frame.

In [20]:
df.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess,insomnia
0,8,f,39,65,80,72.5,91.0,90.0,93.0,83.5,93.0,90.0,9,13,2,True
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50.0,75.0,50.0,4,11,7,True
2,18,f,31,90,95,92.5,89.5,90.0,86.0,81.0,89.0,88.0,10,9,3,True
3,22,f,35,100,75,87.5,89.5,NaN,71.0,80.0,88.0,80.0,13,8,20,True
4,27,f,74,60,65,62.5,68.5,49.0,61.0,49.0,65.0,49.0,13,9,12,True

## Split-apply-combine

In [23]:
# Split
grouped = df.groupby('insomnia')

In [25]:
# Apply (mean function) and combine
grouped.mean()

,participant number,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
insomnia,,,,,,,,,,,,,,
False,51.61039,37.142857,83.441558,79.480519,81.461039,73.902597,56.238806,70.603896,58.443662,73.850649,59.27027,25.675325,3.922078,7.181818
True,53.40000,40.320000,82.000000,70.200000,76.100000,78.340000,67.735294,72.780000,70.181818,77.080000,70.00000,11.680000,9.440000,7.640000

Note that now the indices are `False` and `True` and the indices have the name `insomnia`.

In [26]:
# Reset the index
grouped.mean().reset_index()

,insomnia,participant number,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess
0,False,51.61039,37.142857,83.441558,79.480519,81.461039,73.902597,56.238806,70.603896,58.443662,73.850649,59.27027,25.675325,3.922078,7.181818
1,True,53.40000,40.320000,82.000000,70.200000,76.100000,78.340000,67.735294,72.780000,70.181818,77.080000,70.00000,11.680000,9.440000,7.640000

In [27]:
grouped['percent correct'].mean().reset_index()

   insomnia  percent correct
0     False        81.461039
1      True        76.100000

In [28]:
# Method chaining
df.groupby('insomnia')['percent correct'].mean().reset_index()

   insomnia  percent correct
0     False        81.461039
1      True        76.100000

In [30]:
df['within insomnia group rank'] = grouped['percent correct'].rank()
df.head()

,participant number,gender,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess,insomnia,within insomnia group rank
0,8,f,39,65,80,72.5,91.0,90.0,93.0,83.5,93.0,90.0,9,13,2,True,11.0
1,16,m,42,90,90,90.0,75.5,55.5,70.5,50.0,75.0,50.0,4,11,7,True,21.5
2,18,f,31,90,95,92.5,89.5,90.0,86.0,81.0,89.0,88.0,10,9,3,True,23.0
3,22,f,35,100,75,87.5,89.5,NaN,71.0,80.0,88.0,80.0,13,8,20,True,19.5
4,27,f,74,60,65,62.5,68.5,49.0,61.0,49.0,65.0,49.0,13,9,12,True,3.5

In [33]:
df_sorted = df.sort_values(by=['insomnia', 'percent correct'])

df_sorted[['insomnia', 'percent correct', 'within insomnia group rank']]

     insomnia  percent correct  within insomnia group rank
81      False             40.0                         1.0
94      False             55.0                         2.0
39      False             57.5                         3.0
76      False             60.0                         4.5
96      False             60.0                         4.5
86      False             62.5                         6.5
101     False             62.5                         6.5
41      False             65.0                         8.0
28      False             67.5                         9.5
50      False             67.5                         9.5
34      False             70.0                        11.5
100     False             70.0                        11.5
25      False             72.5                        15.0
52      False             72.5                        15.0
53      False             72.5                        15.0
87      False             72.5                        15.0
91      False             72.5                        15.0
27      False             75.0                        19.0
49      False             75.0                        19.0
99      False             75.0                        19.0
36      False             77.5                        25.0
43      False             77.5                        25.0
51      False             77.5                        25.0
64      False             77.5                        25.0
68      False             77.5                        25.0
78      False             77.5                        25.0
79      False             77.5                        25.0
85      False             77.5                        25.0
97      False             77.5                        25.0
44      False             80.0                        31.5
..        ...              ...                         ...
77      False             95.0                        72.0
73      False             97.5                        74.0
33      False            100.0                        76.0
70      False            100.0                        76.0
75      False            100.0                        76.0
23       True             45.0                         1.0
5        True             50.0                         2.0
4        True             62.5                         3.5
10       True             62.5                         3.5
14       True             65.0                         5.0
7        True             67.5                         6.0
15       True             70.0                         8.5
16       True             70.0                         8.5
20       True             70.0                         8.5
24       True             70.0                         8.5
0        True             72.5                        11.0
9        True             75.0                        12.5
19       True             75.0                        12.5
12       True             80.0                        15.0
13       True             80.0                        15.0
17       True             80.0                        15.0
6        True             82.5                        17.0
18       True             85.0                        18.0
3        True             87.5                        19.5
22       True             87.5                        19.5
1        True             90.0                        21.5
8        True             90.0                        21.5
2        True             92.5                        23.0
11       True             95.0                        24.0
21       True             97.5                        25.0

[102 rows x 3 columns]

In [34]:
def coeff_of_var(data):
    """Compute coefficient of variation for an array of data."""""
    return np.std(data) / np.mean(data)

In [36]:
df.groupby('insomnia').agg(coeff_of_var).reset_index()

,insomnia,participant number,age,correct hit percentage,correct reject percentage,percent correct,confidence when correct hit,confidence incorrect hit,confidence correct reject,confidence incorrect reject,confidence when correct,confidence when incorrect,sci,psqi,ess,within insomnia group rank
0,False,0.586191,0.384262,0.166784,0.184061,0.138785,0.195978,0.350286,0.204312,0.298216,0.187304,0.262509,0.175245,0.577869,0.571566,0.566949
1,True,0.536117,0.313853,0.218834,0.325760,0.171856,0.156219,0.225440,0.222827,0.211512,0.160061,0.197484,0.381907,0.299741,0.681514,0.552777

In [37]:
for name, group in df.groupby(['gender', 'insomnia']):
    print(name, ':', group['percent correct'].mean())

('f', False) : 82.04545454545455
('f', True) : 73.94736842105263
('m', False) : 80.0
('m', True) : 82.91666666666667

# Tidying untidy data

In [41]:
# Another dataset

!head -20 data/reeves_gradient_width_various_methods.csv

# Raw data from Reeves, et al., Dev. Cell, 22, 544, 2012.
#
# These data were used to create figure 1F.
#
# The first row of column headings contains the genotypes.
# The second row contains the staining/visualization method.
# The data give the computed gradient width as parametrized by
# sigma (see the original paper).
#
# Kindly provided by Greg Reeves (NC State) and Nathanie Trisnadi and Angela Stathopoulos (Caltech)
wt,wt,dl1/+; dl-venus/+,dl1/+; dl-venus/+,dl1/+; dl-venus/+,dl1/+; dl-gfp/+,dl1/+; dl-gfp/+,dl1/+; dl-gfp/+
wholemounts,cross-sections,anti-Dorsal,anti-Venus,Venus (live),anti-Dorsal,anti-GFP,GFP (live)
0.1288,0.1327,0.1482,0.1632,0.1666,0.2248,0.2389,0.2412
0.1554,0.1457,0.1503,0.1671,0.1753,0.1891,0.2035,0.1942
0.1306,0.1447,0.1577,0.1704,0.1705,0.1705,0.1943,0.2186
0.1413,0.1282,0.1711,0.1779,,0.1735,0.2,0.2104
0.1557,0.1487,0.1342,0.1483,,0.2135,0.256,0.2463
0.1689,0.1203,0.1773,0.1831,,0.2129,0.2309,0.202
0.1417,0.1315,0.1705,0.1783,,0.1782,0.1949,
0.1315,0.1463,0.1596,0.1667,,0.2011,0.2216,

We need to load in the dataset without the comments, and indicating which rows are the header.

In [42]:
df = pd.read_csv('data/reeves_gradient_width_various_methods.csv',
                 comment = '#', header = [0, 1])

df.head()

           wt                dl1/+; dl-venus/+                          \
  wholemounts cross-sections       anti-Dorsal anti-Venus Venus (live)
0      0.1288         0.1327            0.1482     0.1632       0.1666
1      0.1554         0.1457            0.1503     0.1671       0.1753
2      0.1306         0.1447            0.1577     0.1704       0.1705
3      0.1413         0.1282            0.1711     0.1779          NaN
4      0.1557         0.1487            0.1342     0.1483          NaN

  dl1/+; dl-gfp/+
      anti-Dorsal anti-GFP GFP (live)
0          0.2248   0.2389     0.2412
1          0.1891   0.2035     0.1942
2          0.1705   0.1943     0.2186
3          0.1735   0.2000     0.2104
4          0.2135   0.2560     0.2463

In [45]:
pd.melt(df, value_name='gradient width',
       var_name=['genotype', 'method'])

             genotype       method  gradient width
0                  wt  wholemounts          0.1288
1                  wt  wholemounts          0.1554
2                  wt  wholemounts          0.1306
3                  wt  wholemounts          0.1413
4                  wt  wholemounts          0.1557
5                  wt  wholemounts          0.1689
6                  wt  wholemounts          0.1417
7                  wt  wholemounts          0.1315
8                  wt  wholemounts          0.1664
9                  wt  wholemounts          0.1560
10                 wt  wholemounts          0.1479
11                 wt  wholemounts          0.1475
12                 wt  wholemounts          0.1347
13                 wt  wholemounts          0.1129
14                 wt  wholemounts          0.1250
15                 wt  wholemounts          0.1648
16                 wt  wholemounts          0.1555
17                 wt  wholemounts          0.1403
18                 wt  wholemounts          0.1096
19                 wt  wholemounts          0.1779
20                 wt  wholemounts          0.1244
21                 wt  wholemounts          0.1708
22                 wt  wholemounts          0.1691
23                 wt  wholemounts          0.1300
24                 wt  wholemounts             NaN
25                 wt  wholemounts             NaN
26                 wt  wholemounts             NaN
27                 wt  wholemounts             NaN
28                 wt  wholemounts             NaN
29                 wt  wholemounts             NaN
...               ...          ...             ...
1186  dl1/+; dl-gfp/+   GFP (live)             NaN
1187  dl1/+; dl-gfp/+   GFP (live)             NaN
1188  dl1/+; dl-gfp/+   GFP (live)             NaN
1189  dl1/+; dl-gfp/+   GFP (live)             NaN
1190  dl1/+; dl-gfp/+   GFP (live)             NaN
1191  dl1/+; dl-gfp/+   GFP (live)             NaN
1192  dl1/+; dl-gfp/+   GFP (live)             NaN
1193  dl1/+; dl-gfp/+   GFP (live)             NaN
1194  dl1/+; dl-gfp/+   GFP (live)             NaN
1195  dl1/+; dl-gfp/+   GFP (live)             NaN
1196  dl1/+; dl-gfp/+   GFP (live)             NaN
1197  dl1/+; dl-gfp/+   GFP (live)             NaN
1198  dl1/+; dl-gfp/+   GFP (live)             NaN
1199  dl1/+; dl-gfp/+   GFP (live)             NaN
1200  dl1/+; dl-gfp/+   GFP (live)             NaN
1201  dl1/+; dl-gfp/+   GFP (live)             NaN
1202  dl1/+; dl-gfp/+   GFP (live)             NaN
1203  dl1/+; dl-gfp/+   GFP (live)             NaN
1204  dl1/+; dl-gfp/+   GFP (live)             NaN
1205  dl1/+; dl-gfp/+   GFP (live)             NaN
1206  dl1/+; dl-gfp/+   GFP (live)             NaN
1207  dl1/+; dl-gfp/+   GFP (live)             NaN
1208  dl1/+; dl-gfp/+   GFP (live)             NaN
1209  dl1/+; dl-gfp/+   GFP (live)             NaN
1210  dl1/+; dl-gfp/+   GFP (live)             NaN
1211  dl1/+; dl-gfp/+   GFP (live)             NaN
1212  dl1/+; dl-gfp/+   GFP (live)             NaN
1213  dl1/+; dl-gfp/+   GFP (live)             NaN
1214  dl1/+; dl-gfp/+   GFP (live)             NaN
1215  dl1/+; dl-gfp/+   GFP (live)             NaN

[1216 rows x 3 columns]

In [46]:
df_tidy = pd.melt(
    df, value_name="gradient width", var_name=["genotype", "method"]
)

df_tidy = df_tidy.dropna()

df_tidy.head()

  genotype       method  gradient width
0       wt  wholemounts          0.1288
1       wt  wholemounts          0.1554
2       wt  wholemounts          0.1306
3       wt  wholemounts          0.1413
4       wt  wholemounts          0.1557

In [47]:
%load_ext watermark
%watermark -v -p numpy,pandas,jupyterlab

CPython 3.7.7
IPython 7.13.0

numpy 1.18.1
pandas 0.24.2
jupyterlab 1.2.6